def decrypt(text, key):
    key_len = len(key)
    key_int = [ord(i) for i in key]
    text_int = [ord(i) for i in text]
    plaintext = ''
    for i in range(len(text_int)):
        value = (text_int[i] - key_int[i % key_len]) % 26
        plaintext += chr(value + 65)
    return plaintext

pas=decrypt('AP QYM MSX JOSN LRAC, QYM WSXSQWN LY TBWKC DZO NSYOFOJO USHRWB.LRAC AC SX AWHYJDSXL PABKD KDWZ AX LRAC TYFEK KKCAQFWWXL.DZO SMLESV TYFEK KKCAQFWWXL MSX TO XYMXV SF DZO HNX PAVWZJYNSVOV SF DZO VOVSUKLOV CWMLSGX UKDVWN TYFEK KKCAQFWWXL YF DZOHOSBD MJIHDGQJKHRQ ZSQW YF MSXNKK.K HKKCOYJN AC FOWNWN LY GZWX LRW ZVP XSDO. OO HBGFANW DZSKZSCKGGBV SF OFMJIHDWN XYJW SD LRW OFN GP LRAC EOKCSQW NWXGDWN SCO. DZO HKKCOYJN ZKK LWOF OFMJIHDWN MCAXY DZO JCS MJIHDGCQCLOEGADZ DZO KDSDWN JCS ZMLDSU WGNMVMC F KFN HETVAM WHHYFOFD W.IGEJ DSCC SK DG GJSLO QYMB GGF ZQDZYF ZJYYBSW LRSD TBWKCC LRWOFMJIHDAYF YX DZO HKKCOYJN AX GBVOJ DG BWKV DZO HNX PAVW.KDDZYMQZ DZO JCS WGNMVMC F SK VSBYO AD ESYRL WSUW CWXKO LY LBQDG PSMLYJSRO AD. LY WKKO LRAC HBGMWCK, GW GGEDN DSCO LY HBGFANWIGE OSLR LRW LWVGG KDSDWN SNVSLSGXSV JCS WGNMVA KTM SXV N ORAMZRSFW LWOF EKOV SF K UYEZDOLODI VSXPWBWXL MGXLOPD TEL DZKL RSFWLWOF QWXWBSDWN OSLR LRW CSWW LSN JKFNGW HBAWW QWXWBSDGB SC OKKEKOV DG QWXWBSDW X. EKQLW DZOQ RWVH IGE LY XKUDGBAJW X?,'SKSK')
print(pas)